name: Continuous Integration - CI

on:
  push:
    branches: [ feat/test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn
      
      - name: Running tests
        run: yarn test:ci

      - name: Running eslint
        run: yarn lint

      - name: Build project
        run: yarn build

  # trigger_deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: success()
  #   steps:
  #     - name: Trigger CD workflow
  #       uses: peter-evans/repository-dispatch@v2
  #       with:
  #         token: ${{ secrets.TOKEN }}
  #         event-type: deploy