name: Vercel Preview Deployment

env:
  ## ID da organização no Vercel
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

  ## ID do projeto no Vercel
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - stage

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn

      - name: Running eslint
        run: yarn lint

      - name: Running tests
        run: yarn test:ci

      - name: Build project
        run: yarn build

  Deploy-Preview:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
